"""add_user_funcao_and_creation_request

Revision ID: a90e9c8eb0e6
Revises: 50f55eb74867
Create Date: 2026-07-20 10:48:20.016629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90e9c8eb0e6'
down_revision: Union[str, Sequence[str], None] = '50f55eb74867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes_criacao_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('perfil_id', sa.String(), nullable=False),
    sa.Column('especialidade', sa.String(), nullable=True),
    sa.Column('funcao', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_criacao_usuario_id'), 'solicitacoes_criacao_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_criacao_usuario_username'), 'solicitacoes_criacao_usuario', ['username'], unique=False)
    op.add_column('usuarios', sa.Column('funcao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'funcao')
    op.drop_index(op.f('ix_solicitacoes_criacao_usuario_username'), table_name='solicitacoes_criacao_usuario')
    op.drop_index(op.f('ix_solicitacoes_criacao_usuario_id'), table_name='solicitacoes_criacao_usuario')
    op.drop_table('solicitacoes_criacao_usuario')
    # ### end Alembic commands ###
