"""add_fields_to_user_creation_request

Revision ID: f2e1921a9b72
Revises: a90e9c8eb0e6
Create Date: 2026-07-20 11:32:23.104818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e1921a9b72'
down_revision: Union[str, Sequence[str], None] = 'a90e9c8eb0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes_criacao_usuario', sa.Column('tipo', sa.String(), nullable=False, server_default='CRIACAO'))
    op.add_column('solicitacoes_criacao_usuario', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('solicitacoes_criacao_usuario', sa.Column('campos_modificados', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitacoes_criacao_usuario', 'campos_modificados')
    op.drop_column('solicitacoes_criacao_usuario', 'user_id')
    op.drop_column('solicitacoes_criacao_usuario', 'tipo')
    # ### end Alembic commands ###

